# -*- coding: utf-8 -*-
"""train_yolov8s_seg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1px6TcHsz-bUvphFRC2uTbjaxyOf3sXsi
"""

!yolo task=segment mode=train model=yolov8s-seg.pt \
    data=/content/drive/MyDrive/TrafficSignal/segmentation_updated/data.yaml \
    epochs=250 imgsz=640 save=True