# -*- coding: utf-8 -*-
"""data_split_seg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL1-gQgBF_imL2Mr4Y7RaA4Mp0xXPZSi
"""

import os
import random
import shutil

# Paths
base_path = "/content/drive/MyDrive/TrafficSignal/segmentation_updated"
image_dir = os.path.join(base_path, "images/train")
label_dir = os.path.join(base_path, "labels/train")

# Output paths
train_img_out = os.path.join(base_path, "images/train")
val_img_out = os.path.join(base_path, "images/val")
train_lbl_out = os.path.join(base_path, "labels/train")
val_lbl_out = os.path.join(base_path, "labels/val")

# Ensure dirs
os.makedirs(val_img_out, exist_ok=True)
os.makedirs(val_lbl_out, exist_ok=True)

# Split 80/20
all_images = [f for f in os.listdir(image_dir) if f.endswith(".png")]
random.shuffle(all_images)
val_split = int(0.2 * len(all_images))
val_images = all_images[:val_split]

# Move validation images and corresponding labels
for img_name in val_images:
    label_name = img_name.replace(".png", ".txt")

    shutil.move(os.path.join(image_dir, img_name), os.path.join(val_img_out, img_name))
    shutil.move(os.path.join(label_dir, label_name), os.path.join(val_lbl_out, label_name))

print("Split complete!")